### ISSUE TITLE
How to find APNs topic

### ISSUE THREAD

**Issue by kevxlreee** [a2/passcards-swift#6]
Unfortunately I'm not too experienced with APNs - could you please detail how to retrieve the APNs topic to set the env variable?

I have created an App ID with Push (prod) capability, and downloaded that production SSL certificate. However I am unable to extract the topic from this.

Thanks

**Comment by a2** [comment]
You first need to create an auth key [here](https://developer.apple.com/account/ios/authkey/) and choose APNs as the service to enable. Then the APNs topic is the Key ID. Hope that helps.

![artboard](https://user-images.githubusercontent.com/241156/44325231-7877e200-a458-11e8-8542-1397957b9e26.png)

**Comment by kevxlreee** [comment]
Got it! Thanks!
